# Generated by Django 5.2.8 on 2025-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='demografia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
